In [ ]:
!pip install transformers accelerate datasets evaluate

In [ ]:
!pip install bitsandbytes

In [ ]:
!nvidia-smi

Thu May  9 17:13:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                      Off | 00000000:00:03.0 Off |                    0 |
| N/A   51C    P8              12W /  72W |      1MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

In [ ]:
name = 'ai-forever/ruGPT-3.5-13B'
# name = 'ai-forever/mGPT-13B'
#name = 'ai-forever/rugpt3small_based_on_gpt2'

# Loading the model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
    name,
    device_map='cuda:0',
    load_in_8bit=True,
    offload_folder='./_tmp',
    max_memory={0: f'{int(torch.cuda.mem_get_info()[0] / 1024 ** 3) - 2}GB'},
    cache_dir="/content/.cache/huggingface"
)
tokenizer = AutoTokenizer.from_pretrained(name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/782 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.


pytorch_model.bin.index.json:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

pytorch_model-00001-of-00006.bin:   0%|          | 0.00/9.92G [00:00<?, ?B/s]

pytorch_model-00002-of-00006.bin:   0%|          | 0.00/9.68G [00:00<?, ?B/s]

pytorch_model-00003-of-00006.bin:   0%|          | 0.00/9.68G [00:00<?, ?B/s]

pytorch_model-00004-of-00006.bin:   0%|          | 0.00/10.0G [00:00<?, ?B/s]

pytorch_model-00005-of-00006.bin:   0%|          | 0.00/9.79G [00:00<?, ?B/s]

pytorch_model-00006-of-00006.bin:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/933 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.77M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/582 [00:00<?, ?B/s]

In [ ]:
import pandas as pd

df = pd.read_csv(r'./stimuli_2018_test1.csv')[['Prot', 'Sent', 'Group', 'N1', 'N2', 'Pred', 'Code', 'Sentence']]
df = df.dropna(axis=0)

In [ ]:
#df[df['Code'] == 'S_S-S']['Sentence'].to_list()

In [ ]:
import datasets
import numpy as np
import torch
from torch.nn import CrossEntropyLoss
from transformers import AutoModelForCausalLM, AutoTokenizer

import evaluate
from evaluate import logging

from tqdm.auto import tqdm

In [ ]:
def get_log_proba(text):
    all_tokens = tokenizer(f', {text},', return_tensors='pt').input_ids.to('cuda')
    prev_tokens = all_tokens[:, :-1]
    next_tokens = all_tokens[:, 1:]
    with torch.inference_mode():
        model_out = model(prev_tokens)
        tokens_log_proba = torch.gather(torch.log_softmax(model_out.logits, -1), 2, next_tokens.unsqueeze(-1))
        phrase_log_proba = tokens_log_proba.sum().item()

        #loss = model_out.loss
        #perplexity = torch.exp(loss)
        #phrase_log_proba = perplexity.item()
    return phrase_log_proba

In [ ]:
df['leftA'] = df['Sentence'].apply(lambda a: ' '.join(a.strip().split()[:4]))
df['rightA'] = df['Sentence'].apply(lambda a: ' '.join(a.strip().split()[4:]))

In [ ]:
df#['Sentence'].to_list()

Prot  Sent  Group N1 N2 Pred   Code  \
0     1.0   1.0    1.0  S  S    S  S_S-S   
1     2.0   1.0    1.0  S  S    P  P_S-S   
2     3.0   1.0    1.0  S  P    S  S_S-P   
3     4.0   1.0    1.0  S  P    P  P_S-P   
4     5.0   1.0    1.0  P  S    S  S_P-S   
..    ...   ...    ... .. ..  ...    ...   
507   4.0  64.0    2.0  S  P    S  S_S-P   
508   5.0  64.0    2.0  S  P    P  P_S-P   
509   6.0  64.0    2.0  P  S    S  S_P-S   
510   7.0  64.0    2.0  P  S    P  P_P-S   
511   8.0  64.0    2.0  P  P    S  S_P-P   

                                              Sentence  \
0    Абонемент на концерт был дорогим из-за участия...   
1    Абонемент на концерт были дорогими из-за участ...   
2    Абонемент на концерты был дорогим из-за участи...   
3    Абонемент на концерты были дорогими из-за учас...   
4    Абонементы на концерт был дорогим из-за участи...   
..                                                 ...   
507  Скидка от авиакомпаний была беспрецедентной из...   
508  Скидка от авиакомпаний были беспрецедентными и...   
509  Скидки от авиакомпании была беспрецедентной из...   
510  Скидки от авиакомпании были беспрецедентными и...   
511  Скидки от авиакомпаний была беспрецедентной из...   

                           leftA  \
0       Абонемент на концерт был   
1      Абонемент на концерт были   
2      Абонемент на концерты был   
3     Абонемент на концерты были   
4      Абонементы на концерт был   
..                           ...   
507  Скидка от авиакомпаний была   
508  Скидка от авиакомпаний были   
509  Скидки от авиакомпании была   
510  Скидки от авиакомпании были   
511  Скидки от авиакомпаний была   

                                                rightA  
0           дорогим из-за участия популярных артистов.  
1          дорогими из-за участия популярных артистов.  
2           дорогим из-за участия популярных артистов.  
3          дорогими из-за участия популярных артистов.  
4           дорогим из-за участия популярных артистов.  
..                                                 ...  
507  беспрецедентной из-за недавнего крушения самол...  
508  беспрецедентными из-за недавнего крушения само...  
509  беспрецедентной из-за недавнего крушения самол...  
510  беспрецедентными из-за недавнего крушения само...  
511  беспрецедентной из-за недавнего крушения самол...  

[512 rows x 10 columns]

In [ ]:
df.tail(16)#['Sentence'].to_list()

Prot  Sent  Group N1 N2 Pred   Code  \
496   1.0  63.0    2.0  P  P    S  S_P-P   
497   2.0  63.0    2.0  P  P    P  P_P-P   
498   3.0  63.0    2.0  S  S    S  S_S-S   
499   4.0  63.0    2.0  S  S    P  P_S-S   
500   5.0  63.0    2.0  S  P    S  S_S-P   
501   6.0  63.0    2.0  S  P    P  P_S-P   
502   7.0  63.0    2.0  P  S    S  S_P-S   
503   8.0  63.0    2.0  P  S    P  P_P-S   
504   1.0  64.0    2.0  P  P    P  P_P-P   
505   2.0  64.0    2.0  S  S    S  S_S-S   
506   3.0  64.0    2.0  S  S    P  P_S-S   
507   4.0  64.0    2.0  S  P    S  S_S-P   
508   5.0  64.0    2.0  S  P    P  P_S-P   
509   6.0  64.0    2.0  P  S    S  S_P-S   
510   7.0  64.0    2.0  P  S    P  P_P-S   
511   8.0  64.0    2.0  P  P    S  S_P-P   

                                              Sentence  \
496  Скандалы из-за статей был масштабным в глазах ...   
497  Скандалы из-за статей были масштабными в глаза...   
498  Скандал из-за статьи был масштабным в глазах н...   
499  Скандал из-за статьи были масштабными в глазах...   
500  Скандал из-за статей был масштабным в глазах н...   
501  Скандал из-за статей были масштабными в глазах...   
502  Скандалы из-за статьи был масштабным в глазах ...   
503  Скандалы из-за статьи были масштабными в глаза...   
504  Скидки от авиакомпаний были беспрецедентными и...   
505  Скидка от авиакомпании была беспрецедентной из...   
506  Скидка от авиакомпании были беспрецедентными и...   
507  Скидка от авиакомпаний была беспрецедентной из...   
508  Скидка от авиакомпаний были беспрецедентными и...   
509  Скидки от авиакомпании была беспрецедентной из...   
510  Скидки от авиакомпании были беспрецедентными и...   
511  Скидки от авиакомпаний была беспрецедентной из...   

                       left                                              right  
496   Скандалы из-за статей  был масштабным в глазах непосредственных участ...  
497   Скандалы из-за статей  были масштабными в глазах непосредственных уча...  
498    Скандал из-за статьи  был масштабным в глазах непосредственных участ...  
499    Скандал из-за статьи  были масштабными в глазах непосредственных уча...  
500    Скандал из-за статей  был масштабным в глазах непосредственных участ...  
501    Скандал из-за статей  были масштабными в глазах непосредственных уча...  
502   Скандалы из-за статьи  был масштабным в глазах непосредственных участ...  
503   Скандалы из-за статьи  были масштабными в глазах непосредственных уча...  
504  Скидки от авиакомпаний  были беспрецедентными из-за недавнего крушения...  
505  Скидка от авиакомпании  была беспрецедентной из-за недавнего крушения ...  
506  Скидка от авиакомпании  были беспрецедентными из-за недавнего крушения...  
507  Скидка от авиакомпаний  была беспрецедентной из-за недавнего крушения ...  
508  Скидка от авиакомпаний  были беспрецедентными из-за недавнего крушения...  
509  Скидки от авиакомпании  была беспрецедентной из-за недавнего крушения ...  
510  Скидки от авиакомпании  были беспрецедентными из-за недавнего крушения...  
511  Скидки от авиакомпаний  была беспрецедентной из-за недавнего крушения ...

In [ ]:
df['p_w1'] = [get_log_proba(w) for w in tqdm(df.left)]
df['p_w2'] = [get_log_proba(w) for w in tqdm(df.right)]
df['p_phrase'] = [get_log_proba(w) for w in tqdm(df['Sentence'])]

  0%|          | 0/512 [00:00<?, ?it/s]

  0%|          | 0/512 [00:00<?, ?it/s]

  0%|          | 0/512 [00:00<?, ?it/s]

In [ ]:
df['compatibility_scoreA'] = df['p_phrase'] - df['p_w2A'] - df['p_w1A']

In [ ]:
df.to_csv('gpt13b_score.csv')

In [ ]:
df[['Code','p_phrase']].groupby('Code')\
            .agg(['mean','std'])

p_phrase          
            mean       std
Code                      
P_P-P -72.876953  7.648326
P_P-S -72.631836  7.774382
P_S-P -76.674805  7.527277
P_S-S -76.504395  8.525189
S_P-P -78.096680  7.803649
S_P-S -77.357910  7.823506
S_S-P -72.887207  7.310530
S_S-S -71.746582  8.957628

In [ ]:
df[['Code','compatibility_score']].groupby('Code')\
            .agg(['mean','std'])

compatibility_score          
                     mean       std
Code                               
P_P-P            8.322266  3.544970
P_P-S            9.041016  3.710921
P_S-P            5.049316  3.617763
P_S-S            4.325684  3.530931
S_P-P            3.242432  3.425112
S_P-S            4.448486  3.357410
S_S-P            8.959961  3.578687
S_S-S            9.164795  3.416710

## Simple perplexity

In [ ]:
predictions = df['Sentence'].to_list()
tokenizer.pad_token = tokenizer.eos_token

In [ ]:
encodings = tokenizer(
    predictions,
    add_special_tokens=False,
    padding=True,
    truncation=True,
    max_length=32,
    return_tensors="pt",
    return_attention_mask=True,
    ).to('cuda')

encoded_texts = encodings["input_ids"]
attn_masks = encodings["attention_mask"]

batch_size = 12

ppls = []
loss_fct = CrossEntropyLoss(reduction="none")

for start_index in logging.tqdm(range(0, len(encoded_texts), batch_size)):
    end_index = min(start_index + batch_size, len(encoded_texts))
    encoded_batch = encoded_texts[start_index:end_index]
    attn_mask = attn_masks[start_index:end_index]

    labels = encoded_batch

    with torch.no_grad():
        out_logits = model(encoded_batch, attention_mask=attn_mask).logits

    shift_logits = out_logits[..., :-1, :].contiguous()
    shift_labels = labels[..., 1:].contiguous()
    shift_attention_mask_batch = attn_mask[..., 1:].contiguous()

    perplexity_batch = torch.exp(
        (loss_fct(shift_logits.transpose(1, 2), shift_labels) * shift_attention_mask_batch).sum(1)
        / shift_attention_mask_batch.sum(1)
    )

    ppls += perplexity_batch.tolist()

  0%|          | 0/43 [00:00<?, ?it/s]

In [ ]:
df['GPT3'] = ppls

In [ ]:
df[['Code','GPT3']].groupby('Code')\
            .agg(['mean','std'])

GPT3           
            mean        std
Code                       
P_P-P  44.629883  29.483157
P_P-S  47.082275  31.946271
P_S-P  72.231201  50.386582
P_S-S  78.085938  56.949405
S_P-P  81.658936  68.720049
S_P-S  82.544189  63.532525
S_S-P  52.054688  33.589705
S_S-S  51.966553  42.421811

In [ ]:
df.to_csv(r'./stimuli_2018_test2_alt_withpred.csv', encoding='utf8')

In [ ]:
df

## Quasi-Perplexity

In [ ]:
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("DeepPavlov/rubert-base-cased")
model = AutoModelForMaskedLM.from_pretrained("DeepPavlov/rubert-base-cased")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/24.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/642 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/1.65M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/714M [00:00<?, ?B/s]

In [ ]:
tokenizer("было", return_tensors="pt")

{'input_ids': tensor([[ 101, 3332,  102]]), 'token_type_ids': tensor([[0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1]])}

In [ ]:
plural = 3294 #были
singular_m = 2067 #был
singular_f = 3370 #была
singular_i = 3332 #было

buli = {'были':3294,
        'был':2067,
        'была':3370,
        'было':3332,
        }

In [ ]:
model.to('cuda')

In [ ]:
inputs = tokenizer("Абонементы на концерт [MASK] дорогими .", return_tensors="pt").to('cuda')

mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]

with torch.no_grad():
    logits = model(**inputs).logits

print('был --', logits[0, mask_token_index][0][singular_m])
print('были --', logits[0, mask_token_index][0][plural])

был -- tensor(6.7170, device='cuda:0')
были -- tensor(14.8506, device='cuda:0')


In [ ]:
df.head()

Prot  Sent  Group N1 N2 Pred   Code  \
0   1.0   1.0    1.0  S  S    S  S_S-S   
1   2.0   1.0    1.0  S  S    P  P_S-S   
2   3.0   1.0    1.0  S  P    S  S_S-P   
3   4.0   1.0    1.0  S  P    P  P_S-P   
4   5.0   1.0    1.0  P  S    S  S_P-S   

                                            Sentence                   left  \
0  Абонемент на концерт был дорогим из-за участия...   Абонемент на концерт   
1  Абонемент на концерт были дорогими из-за участ...   Абонемент на концерт   
2  Абонемент на концерты был дорогим из-за участи...  Абонемент на концерты   
3  Абонемент на концерты были дорогими из-за учас...  Абонемент на концерты   
4  Абонементы на концерт был дорогим из-за участи...  Абонементы на концерт   

                                              right  
0    был дорогим из-за участия популярных артистов.  
1  были дорогими из-за участия популярных артистов.  
2    был дорогим из-за участия популярных артистов.  
3  были дорогими из-за участия популярных артистов.  
4    был дорогим из-за участия популярных артистов.

In [ ]:
df[df['is_true'] == False]

In [ ]:
df['is_true'] = df['right'].apply(lambda a: a.startswith('был'))

In [ ]:
df['masked_leftA'] = df['leftA'].apply(lambda a: a+' [MASK]' )

In [ ]:
df['masked_fullA'] = df['Sentence'].apply(lambda a: ' '.join(a.strip().split()[:4])\
                                         +' [MASK] '+\
                                         ' '.join(a.strip().split()[5:]) )

In [ ]:
df['need_to_predict'] = df['rightA'].apply(lambda a: " ".join(a.strip().split()[0:]))

In [ ]:
df['need_to_predict'] = df['rightA'].apply(lambda a: a.strip().split()[0])

In [ ]:
df['need_to_predict'].value_counts()

need_to_predict
приятными      8
просторными    4
ржавыми        4
ржавым         4
привезен       4
              ..
совершены      4
повышены       4
повышен        4
возведён       4
отправлены     4
Name: count, Length: 127, dtype: int64

In [ ]:
tokenizer("было", return_tensors="pt")['input_ids'][0,1]

tensor(3332)

In [ ]:
raw_check = df.groupby(['Sent','Group','Pred']).agg({"need_to_predict":'unique'}).reset_index()
raw_check['token'] = raw_check['need_to_predict'].apply(lambda a: tokenizer(a[0], return_tensors="pt")['input_ids'][0][1:-1] )
raw_check

Sent  Group Pred     need_to_predict                          token
0     1.0    1.0    P          [дорогими]               [tensor(101534)]
1     1.0    1.0    S           [дорогим]                [tensor(58020)]
2     2.0    1.0    P          [обидными]  [tensor(45371), tensor(3359)]
3     2.0    1.0    S           [обидным]  [tensor(45371), tensor(2010)]
4     3.0    1.0    P         [проделаны]  [tensor(35326), tensor(5242)]
..    ...    ...  ...                 ...                            ...
123  62.0    2.0    S           [написан]                [tensor(29307)]
124  63.0    2.0    P       [масштабными]   [tensor(92662), tensor(852)]
125  63.0    2.0    S        [масштабным]                [tensor(92662)]
126  64.0    2.0    P  [беспрецедентными]  [tensor(45516), tensor(3359)]
127  64.0    2.0    S   [беспрецедентной]  [tensor(45516), tensor(1700)]

[128 rows x 5 columns]

In [ ]:
df

Prot  Sent  Group N1 N2 Pred   Code  \
0     1.0   1.0    1.0  S  S    S  S_S-S   
1     2.0   1.0    1.0  S  S    P  P_S-S   
2     3.0   1.0    1.0  S  P    S  S_S-P   
3     4.0   1.0    1.0  S  P    P  P_S-P   
4     5.0   1.0    1.0  P  S    S  S_P-S   
..    ...   ...    ... .. ..  ...    ...   
507   4.0  64.0    2.0  S  P    S  S_S-P   
508   5.0  64.0    2.0  S  P    P  P_S-P   
509   6.0  64.0    2.0  P  S    S  S_P-S   
510   7.0  64.0    2.0  P  S    P  P_P-S   
511   8.0  64.0    2.0  P  P    S  S_P-P   

                                              Sentence  \
0    Абонемент на концерт был дорогим из-за участия...   
1    Абонемент на концерт были дорогими из-за участ...   
2    Абонемент на концерты был дорогим из-за участи...   
3    Абонемент на концерты были дорогими из-за учас...   
4    Абонементы на концерт был дорогим из-за участи...   
..                                                 ...   
507  Скидка от авиакомпаний была беспрецедентной из...   
508  Скидка от авиакомпаний были беспрецедентными и...   
509  Скидки от авиакомпании была беспрецедентной из...   
510  Скидки от авиакомпании были беспрецедентными и...   
511  Скидки от авиакомпаний была беспрецедентной из...   

                           leftA  \
0       Абонемент на концерт был   
1      Абонемент на концерт были   
2      Абонемент на концерты был   
3     Абонемент на концерты были   
4      Абонементы на концерт был   
..                           ...   
507  Скидка от авиакомпаний была   
508  Скидка от авиакомпаний были   
509  Скидки от авиакомпании была   
510  Скидки от авиакомпании были   
511  Скидки от авиакомпаний была   

                                                rightA  \
0           дорогим из-за участия популярных артистов.   
1          дорогими из-за участия популярных артистов.   
2           дорогим из-за участия популярных артистов.   
3          дорогими из-за участия популярных артистов.   
4           дорогим из-за участия популярных артистов.   
..                                                 ...   
507  беспрецедентной из-за недавнего крушения самол...   
508  беспрецедентными из-за недавнего крушения само...   
509  беспрецедентной из-за недавнего крушения самол...   
510  беспрецедентными из-за недавнего крушения само...   
511  беспрецедентной из-за недавнего крушения самол...   

                           masked_leftA  \
0       Абонемент на концерт был [MASK]   
1      Абонемент на концерт были [MASK]   
2      Абонемент на концерты был [MASK]   
3     Абонемент на концерты были [MASK]   
4      Абонементы на концерт был [MASK]   
..                                  ...   
507  Скидка от авиакомпаний была [MASK]   
508  Скидка от авиакомпаний были [MASK]   
509  Скидки от авиакомпании была [MASK]   
510  Скидки от авиакомпании были [MASK]   
511  Скидки от авиакомпаний была [MASK]   

                                          masked_fullA   need_to_predict  \
0    Абонемент на концерт был [MASK] из-за участия ...           дорогим   
1    Абонемент на концерт были [MASK] из-за участия...          дорогими   
2    Абонемент на концерты был [MASK] из-за участия...           дорогим   
3    Абонемент на концерты были [MASK] из-за участи...          дорогими   
4    Абонементы на концерт был [MASK] из-за участия...           дорогим   
..                                                 ...               ...   
507  Скидка от авиакомпаний была [MASK] из-за недав...   беспрецедентной   
508  Скидка от авиакомпаний были [MASK] из-за недав...  беспрецедентными   
509  Скидки от авиакомпании была [MASK] из-за недав...   беспрецедентной   
510  Скидки от авиакомпании были [MASK] из-за недав...  беспрецедентными   
511  Скидки от авиакомпаний была [MASK] из-за недав...   беспрецедентной   

     left_bert_is_singular  left_bert_is_singular_score  \
0                     True                     2.347879   
1                     True                     0.919863   
2                     True                

In [ ]:
import numpy as np

def test_full(sentence):

    sing_ans = []

    sing = raw_check[(raw_check['Sent'] == sentence['Sent']) &
                     (raw_check['Group'] == sentence['Group']) &
                     (raw_check['Pred'] == 'S')
                     ]['token'].to_list()[0]
    print(sing)
    new_inputs = sentence['masked_leftA'][:-6]
    print(new_inputs, len(sing))
    new_inputs += ''.join(['[MASK]',]*len(sing))
    print(new_inputs)

    inputs = tokenizer(new_inputs, return_tensors="pt").to('cuda')
    mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]
    print(mask_token_index)

    with torch.no_grad():
        logits = model(**inputs).logits

    for enum, i in enumerate(sing):
        sing_ans.append(logits[0, mask_token_index][enum][i].detach().cpu().numpy()
                        )
    sing_ans = np.mean(sing_ans)
    print(sing_ans)

    plur_ans = []
    plur = raw_check[(raw_check['Sent'] == sentence['Sent']) &
                     (raw_check['Group'] == sentence['Group']) &
                     (raw_check['Pred'] == 'P')
                     ]['token'].to_list()[0]
    print(plur)
    new_inputs = sentence['masked_leftA'][:-6]
    print(new_inputs, len(plur))
    new_inputs += ''.join(['[MASK]',]*len(plur))
    print(new_inputs)

    inputs = tokenizer(new_inputs, return_tensors="pt").to('cuda')
    mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]
    print(mask_token_index)

    with torch.no_grad():
        logits = model(**inputs).logits

    for enum, i in enumerate(plur):
        plur_ans.append(logits[0, mask_token_index][enum][i].detach().cpu().numpy()
                        )
    plur_ans = np.mean(plur_ans)

    return [plur_ans, sing_ans]

    #return [logits[0, mask_token_index][0][plur].detach().cpu().numpy(),
    #        logits[0, mask_token_index][0][sing].detach().cpu().numpy(),]

dd = df.apply(lambda a: test_full(a), axis=1 )

tensor([58020])
Абонемент на концерт был  1
Абонемент на концерт был [MASK]
tensor([7], device='cuda:0')
2.347879
tensor([101534])
Абонемент на концерт был  1
Абонемент на концерт был [MASK]
tensor([7], device='cuda:0')
tensor([58020])
Абонемент на концерт были  1
Абонемент на концерт были [MASK]
tensor([7], device='cuda:0')
0.91986257
tensor([101534])
Абонемент на концерт были  1
Абонемент на концерт были [MASK]
tensor([7], device='cuda:0')
tensor([58020])
Абонемент на концерты был  1
Абонемент на концерты был [MASK]
tensor([7], device='cuda:0')
2.4019353
tensor([101534])
Абонемент на концерты был  1
Абонемент на концерты был [MASK]
tensor([7], device='cuda:0')
tensor([58020])
Абонемент на концерты были  1
Абонемент на концерты были [MASK]
tensor([7], device='cuda:0')
0.7385588
tensor([101534])
Абонемент на концерты были  1
Абонемент на концерты были [MASK]
tensor([7], device='cuda:0')
tensor([58020])
Абонементы на концерт был  1
Абонементы на концерт был [MASK]
tensor([7], device='cu

In [ ]:
def test_full(sentence):
    inputs = tokenizer(sentence['masked_left'], return_tensors="pt").to('cuda')
    mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]

    with torch.no_grad():
        logits = model(**inputs).logits

    return [logits[0, mask_token_index][0][buli[sentence['need_to_predict']]].detach().cpu().numpy(),
            logits[0, mask_token_index][0][plural].detach().cpu().numpy(),]

dd = df.apply(lambda a: test_full(a), axis=1 )

In [ ]:
tokenizer('беспрецедентными', return_tensors="pt")

{'input_ids': tensor([[  101, 45516,  3359,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [ ]:
plural = 3294 #были
singular_m = 2067 #был
singular_f = 3370 #была
singular_i = 3332 #было

def test_alt(sentence):
    inputs = tokenizer(sentence['masked_full'], return_tensors="pt").to('cuda')
    #print((inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0][0])
    mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]
    #inputs = tokenizer(sentence['masked_full'], return_tensors="pt").to('cuda')

    with torch.no_grad():
        logits = model(**inputs).logits

    #print(logits[0, mask_token_index][0])

    return [logits[0, mask_token_index][0][plural].detach().cpu().numpy(),
            np.max([
            logits[0, mask_token_index][0][singular_m].detach().cpu().numpy(),
            logits[0, mask_token_index][0][singular_f].detach().cpu().numpy(),
            logits[0, mask_token_index][0][singular_i].detach().cpu().numpy()
            ]),]

dd = df.apply(lambda a: test_alt(a), axis=1 )

In [ ]:
df['left_bert_is_singular'] = [i<j for i,j in dd]

In [ ]:
df['left_bert_is_singular_score'] = [float(i[1]) for i in dd]
df['left_bert_is_plural_score'] = [float(i[0]) for i in dd]

In [ ]:
df

Prot  Sent  Group N1 N2 Pred   Code  \
0     1.0   1.0    1.0  S  S    S  S_S-S   
1     2.0   1.0    1.0  S  S    P  P_S-S   
2     3.0   1.0    1.0  S  P    S  S_S-P   
3     4.0   1.0    1.0  S  P    P  P_S-P   
4     5.0   1.0    1.0  P  S    S  S_P-S   
..    ...   ...    ... .. ..  ...    ...   
507   4.0  64.0    2.0  S  P    S  S_S-P   
508   5.0  64.0    2.0  S  P    P  P_S-P   
509   6.0  64.0    2.0  P  S    S  S_P-S   
510   7.0  64.0    2.0  P  S    P  P_P-S   
511   8.0  64.0    2.0  P  P    S  S_P-P   

                                              Sentence  \
0    Абонемент на концерт был дорогим из-за участия...   
1    Абонемент на концерт были дорогими из-за участ...   
2    Абонемент на концерты был дорогим из-за участи...   
3    Абонемент на концерты были дорогими из-за учас...   
4    Абонементы на концерт был дорогим из-за участи...   
..                                                 ...   
507  Скидка от авиакомпаний была беспрецедентной из...   
508  Скидка от авиакомпаний были беспрецедентными и...   
509  Скидки от авиакомпании была беспрецедентной из...   
510  Скидки от авиакомпании были беспрецедентными и...   
511  Скидки от авиакомпаний была беспрецедентной из...   

                           leftA  \
0       Абонемент на концерт был   
1      Абонемент на концерт были   
2      Абонемент на концерты был   
3     Абонемент на концерты были   
4      Абонементы на концерт был   
..                           ...   
507  Скидка от авиакомпаний была   
508  Скидка от авиакомпаний были   
509  Скидки от авиакомпании была   
510  Скидки от авиакомпании были   
511  Скидки от авиакомпаний была   

                                                rightA  \
0           дорогим из-за участия популярных артистов.   
1          дорогими из-за участия популярных артистов.   
2           дорогим из-за участия популярных артистов.   
3          дорогими из-за участия популярных артистов.   
4           дорогим из-за участия популярных артистов.   
..                                                 ...   
507  беспрецедентной из-за недавнего крушения самол...   
508  беспрецедентными из-за недавнего крушения само...   
509  беспрецедентной из-за недавнего крушения самол...   
510  беспрецедентными из-за недавнего крушения само...   
511  беспрецедентной из-за недавнего крушения самол...   

                           masked_leftA  \
0       Абонемент на концерт был [MASK]   
1      Абонемент на концерт были [MASK]   
2      Абонемент на концерты был [MASK]   
3     Абонемент на концерты были [MASK]   
4      Абонементы на концерт был [MASK]   
..                                  ...   
507  Скидка от авиакомпаний была [MASK]   
508  Скидка от авиакомпаний были [MASK]   
509  Скидки от авиакомпании была [MASK]   
510  Скидки от авиакомпании были [MASK]   
511  Скидки от авиакомпаний была [MASK]   

                                          masked_fullA   need_to_predict  \
0    Абонемент на концерт был [MASK] из-за участия ...           дорогим   
1    Абонемент на концерт были [MASK] из-за участия...          дорогими   
2    Абонемент на концерты был [MASK] из-за участия...           дорогим   
3    Абонемент на концерты были [MASK] из-за участи...          дорогими   
4    Абонементы на концерт был [MASK] из-за участия...           дорогим   
..                                                 ...               ...   
507  Скидка от авиакомпаний была [MASK] из-за недав...   беспрецедентной   
508  Скидка от авиакомпаний были [MASK] из-за недав...  беспрецедентными   
509  Скидки от авиакомпании была [MASK] из-за недав...   беспрецедентной   
510  Скидки от авиакомпании были [MASK] из-за недав...  беспрецедентными   
511  Скидки от авиакомпаний была [MASK] из-за недав...   беспрецедентной   

     left_bert_is_singular  left_bert_is_singular_score  \
0                     True                     2.347879   
1                     True                     0.919863   
2                     True                

In [ ]:
df.to_csv('rubert_score_second.csv')

In [ ]:
df[['Code','left_bert_is_singular']].groupby('Code')\
            .agg(['mean','std'])

left_bert_is_singular          
                       mean       std
Code                                 
P_P-P              0.062500  0.243975
P_P-S              0.093750  0.293785
P_S-P              0.125000  0.333333
P_S-S              0.171875  0.380254
S_P-P              0.734375  0.445157
S_P-S              0.781250  0.416667
S_S-P              0.921875  0.270490
S_S-S              0.921875  0.270490

In [ ]:
df[['Code','full_bert_is_singular']].groupby('Code')\
            .agg(['mean','std'])

full_bert_is_singular          
                       mean       std
Code                                 
P_P-P              0.000000  0.000000
P_P-S              0.000000  0.000000
P_S-P              0.953125  0.213042
P_S-S              0.984375  0.125000
S_P-P              0.000000  0.000000
S_P-S              0.000000  0.000000
S_S-P              0.953125  0.213042
S_S-S              1.000000  0.000000

In [ ]:
df[['Code','bert_score']].groupby('Code')\
            .agg(['mean','std'])

bert_score          
            mean       std
Code                      
P_P-P   6.843250  0.996632
P_P-S   6.549697  1.327452
P_S-P   4.606411  1.638539
P_S-S   4.258953  1.669979
S_P-P   2.731027  1.586208
S_P-S   2.457126  1.564620
S_S-P   3.920699  2.973064
S_S-S   4.319447  2.908580

In [ ]:
df

Prot  Sent  Group N1 N2 Pred   Code  \
0     1.0   1.0    1.0  S  S    S  S_S-S   
1     2.0   1.0    1.0  S  S    P  P_S-S   
2     3.0   1.0    1.0  S  P    S  S_S-P   
3     4.0   1.0    1.0  S  P    P  P_S-P   
4     5.0   1.0    1.0  P  S    S  S_P-S   
..    ...   ...    ... .. ..  ...    ...   
507   4.0  64.0    2.0  S  P    S  S_S-P   
508   5.0  64.0    2.0  S  P    P  P_S-P   
509   6.0  64.0    2.0  P  S    S  S_P-S   
510   7.0  64.0    2.0  P  S    P  P_P-S   
511   8.0  64.0    2.0  P  P    S  S_P-P   

                                              Sentence  \
0    Абонемент на концерт был дорогим из-за участия...   
1    Абонемент на концерт были дорогими из-за участ...   
2    Абонемент на концерты был дорогим из-за участи...   
3    Абонемент на концерты были дорогими из-за учас...   
4    Абонементы на концерт был дорогим из-за участи...   
..                                                 ...   
507  Скидка от авиакомпаний была беспрецедентной из...   
508  Скидка от авиакомпаний были беспрецедентными и...   
509  Скидки от авиакомпании была беспрецедентной из...   
510  Скидки от авиакомпании были беспрецедентными и...   
511  Скидки от авиакомпаний была беспрецедентной из...   

                       left  \
0      Абонемент на концерт   
1      Абонемент на концерт   
2     Абонемент на концерты   
3     Абонемент на концерты   
4     Абонементы на концерт   
..                      ...   
507  Скидка от авиакомпаний   
508  Скидка от авиакомпаний   
509  Скидки от авиакомпании   
510  Скидки от авиакомпании   
511  Скидки от авиакомпаний   

                                                 right  \
0       был дорогим из-за участия популярных артистов.   
1     были дорогими из-за участия популярных артистов.   
2       был дорогим из-за участия популярных артистов.   
3     были дорогими из-за участия популярных артистов.   
4       был дорогим из-за участия популярных артистов.   
..                                                 ...   
507  была беспрецедентной из-за недавнего крушения ...   
508  были беспрецедентными из-за недавнего крушения...   
509  была беспрецедентной из-за недавнего крушения ...   
510  были беспрецедентными из-за недавнего крушения...   
511  была беспрецедентной из-за недавнего крушения ...   

                       masked_left  left_bert  \
0      Абонемент на концерт [MASK]       True   
1      Абонемент на концерт [MASK]       True   
2     Абонемент на концерты [MASK]       True   
3     Абонемент на концерты [MASK]       True   
4     Абонементы на концерт [MASK]      False   
..                             ...        ...   
507  Скидка от авиакомпаний [MASK]      False   
508  Скидка от авиакомпаний [MASK]      False   
509  Скидки от авиакомпании [MASK]      False   
510  Скидки от авиакомпании [MASK]      False   
511  Скидки от авиакомпаний [MASK]      False   

                                                masked  
0    Абонемент на концерт [MASK] дорогим из-за учас...  
1    Абонемент на концерт [MASK] дорогими из-за уча...  
2    Абонемент на концерты [MASK] дорогим из-за уча...  
3    Абонемент на концерты [MASK] дорогими из-за уч...  
4    Абонементы на концерт [MASK] дорогим из-за уча...  
..                                                 ...  
507  Скидка от авиакомпаний [MASK]а беспрецедентной...  
508  Скидка от авиакомпаний [MASK] беспрецедентными...  
509  Скидки от авиакомпании [MASK]а беспрецедентной...  
510  Скидки от авиакомпании [MASK] беспрецедентными...  
511  Скидки от авиакомпаний [MASK]а беспрецедентной...  

[512 rows x 13 columns]

In [ ]:
df['masked'] = df['Sentence'].apply(lambda a: a.replace('были','[MASK]').replace('был','[MASK]'))
df

Prot  Sent  Group N1 N2 Pred   Code  \
0     1.0   1.0    1.0  S  S    S  S_S-S   
1     2.0   1.0    1.0  S  S    P  P_S-S   
2     3.0   1.0    1.0  S  P    S  S_S-P   
3     4.0   1.0    1.0  S  P    P  P_S-P   
4     5.0   1.0    1.0  P  S    S  S_P-S   
..    ...   ...    ... .. ..  ...    ...   
507   4.0  64.0    2.0  S  P    S  S_S-P   
508   5.0  64.0    2.0  S  P    P  P_S-P   
509   6.0  64.0    2.0  P  S    S  S_P-S   
510   7.0  64.0    2.0  P  S    P  P_P-S   
511   8.0  64.0    2.0  P  P    S  S_P-P   

                                              Sentence  \
0    Абонемент на концерт был дорогим из-за участия...   
1    Абонемент на концерт были дорогими из-за участ...   
2    Абонемент на концерты был дорогим из-за участи...   
3    Абонемент на концерты были дорогими из-за учас...   
4    Абонементы на концерт был дорогим из-за участи...   
..                                                 ...   
507  Скидка от авиакомпаний была беспрецедентной из...   
508  Скидка от авиакомпаний были беспрецедентными и...   
509  Скидки от авиакомпании была беспрецедентной из...   
510  Скидки от авиакомпании были беспрецедентными и...   
511  Скидки от авиакомпаний была беспрецедентной из...   

                       left  \
0      Абонемент на концерт   
1      Абонемент на концерт   
2     Абонемент на концерты   
3     Абонемент на концерты   
4     Абонементы на концерт   
..                      ...   
507  Скидка от авиакомпаний   
508  Скидка от авиакомпаний   
509  Скидки от авиакомпании   
510  Скидки от авиакомпании   
511  Скидки от авиакомпаний   

                                                 right  \
0       был дорогим из-за участия популярных артистов.   
1     были дорогими из-за участия популярных артистов.   
2       был дорогим из-за участия популярных артистов.   
3     были дорогими из-за участия популярных артистов.   
4       был дорогим из-за участия популярных артистов.   
..                                                 ...   
507  была беспрецедентной из-за недавнего крушения ...   
508  были беспрецедентными из-за недавнего крушения...   
509  была беспрецедентной из-за недавнего крушения ...   
510  были беспрецедентными из-за недавнего крушения...   
511  была беспрецедентной из-за недавнего крушения ...   

                       masked_left  left_bert  \
0      Абонемент на концерт [MASK]       True   
1      Абонемент на концерт [MASK]       True   
2     Абонемент на концерты [MASK]       True   
3     Абонемент на концерты [MASK]       True   
4     Абонементы на концерт [MASK]      False   
..                             ...        ...   
507  Скидка от авиакомпаний [MASK]      False   
508  Скидка от авиакомпаний [MASK]      False   
509  Скидки от авиакомпании [MASK]      False   
510  Скидки от авиакомпании [MASK]      False   
511  Скидки от авиакомпаний [MASK]      False   

                                                masked  
0    Абонемент на концерт [MASK] дорогим из-за учас...  
1    Абонемент на концерт [MASK] дорогими из-за уча...  
2    Абонемент на концерты [MASK] дорогим из-за уча...  
3    Абонемент на концерты [MASK] дорогими из-за уч...  
4    Абонементы на концерт [MASK] дорогим из-за уча...  
..                                                 ...  
507  Скидка от авиакомпаний [MASK]а беспрецедентной...  
508  Скидка от авиакомпаний [MASK] беспрецедентными...  
509  Скидки от авиакомпании [MASK]а беспрецедентной...  
510  Скидки от авиакомпании [MASK] беспрецедентными...  
511  Скидки от авиакомпаний [MASK]а беспрецедентной...  

[512 rows x 13 columns]

In [ ]:
Абонемент на концерт [MASK] дорогим

был -- tensor(15.6278)
были -- tensor(7.9256)

In [ ]:
Абонемент на концерт [MASK] дорогим

был -- tensor(15.4522)
были -- tensor(8.2000)

In [ ]:
Абонементы на концерт [MASK] дорогим .

был -- tensor(9.8299)
были -- tensor(11.1843)

In [ ]:
inputs = tokenizer("Абонемент на концерт [MASK] дорогим .", return_tensors="pt")

mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]

with torch.no_grad():
    logits = model(**inputs).logits

topk_indices = torch.topk(logits[0, mask_token_index], k=5)

for i,j in zip(topk_indices[0], topk_indices[1]):
    print(tokenizer.decode(j),'::',i)

будет был оказался стал считается :: tensor([15.6367, 15.6278, 15.3595, 14.0973, 13.5299])


In [ ]:
def calculate_perplexity(sentence):
    inputs = tokenizer(sentence, return_tensors='pt')
    with torch.no_grad():
        outputs = model(**inputs, labels=inputs['input_ids'])
    loss = outputs.loss
    perplexity = torch.exp(loss)
    return perplexity.item()

In [ ]:
df['mdeberta-v3-base'] = df['Sentence'].apply(lambda a: calculate_perplexity(a))

In [ ]:
import pandas as pd
dff = pd.read_csv('./results_wiki4.csv')

In [ ]:
dff.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'sentence', 'root', 'root_id',
       'root_number', 'subject', 'subject_id', 'subject_number', 'distractor',
       'distractor_id', 'distractor_number', 'lemmas', 'pos', 'short_version',
       'short_version2', 'misagreed_id', 'predicate'],
      dtype='object')

In [ ]:
dff.drop(['Unnamed: 0.1', 'Unnamed: 0', 'pos', 'lemmas'],axis=1)[:300]#[['short_version','short_version2']]

sentence           root  \
0    В случае, если между сторонами возникает спор ...          может   
1    \n 815-й дальний бомбардировочный авиационный ...      награждён   
2    Бюджет на 2023 год и плановый период 2024 и 20...         принят   
3    Доходы бюджета на 2023 год в исходном варианте...  запланированы   
4    В связи с переформированием дальней авиации в ...        введена   
..                                                 ...            ...   
295  Только прибытие в город подкреплений, направле...         спасло   
296  После стратегической победы при Торо, нейтрали...       возросли   
297  Список 2023 год в спорте описывает спортивные ...      описывает   
298  Цвет в воды в реке ярко-коричневый, так как ис...       являются   
299  В 1832 году произведён в поручики, в 1834 году...      награждён   

     root_id root_number        subject  subject_id subject_number  \
0         19    ['Sing']           спор           7       ['Sing']   
1         30    ['Sing']           полк           6       ['Sing']   
2         12    ['Sing']         Бюджет           0       ['Sing']   
3          9    ['Plur']         Доходы           0       ['Plur']   
4         32    ['Sing']        дивизия          22       ['Sing']   
..       ...         ...            ...         ...            ...   
295       11    ['Sing']       прибытие           1       ['Sing']   
296       24    ['Plur']  нейтрализации           6       ['Plur']   
297        6    ['Sing']         Список           0       ['Sing']   
298       15    ['Plur']           Цвет           0       ['Sing']   
299       11    ['Sing']     произведён           3       ['Sing']   

     distractor  distractor_id distractor_number  \
0        объёме              9          ['Sing']   
1    выполнение              9          ['Sing']   
2           год              3          ['Sing']   
3           год              4          ['Sing']   
4       дивизию             30          ['Sing']   
..          ...            ...               ...   
295       город              3          ['Sing']   
296       шансы             16          ['Plur']   
297         год              3          ['Sing']   
298        воды              2          ['Plur']   
299    поручики              5          ['Plur']   

                                         short_version  \
0    спор об объёме может быть передан на рассмотре...   
1    \n  815-й дальний бомбардировочный авиационный...   
2    Бюджет на 2023 год был принят в ноябре 2022 го...   
3    Доходы бюджета на 2023 год были запланированы ...   
4    55-я авиационная дивизия дальнего действия пер...   
..                                                 ...   
295  Только прибытие в город спасло Неаполь от захвата   
296  , нейтрализации угрозы со стороны Франции и пе...   
297  Список 2023 год описывает спортивные события 2...   
298        Цвет в воды являются торфяные болота . \n\n   
299  произведён в поручики был награждён золотыми ч...   

                                        short_version2  misagreed_id  \
0    Спор об объёме может быть передан на рассмотре...             3   
1    Полк за выполнение награждён орденом « Суворов...             3   
2        Бюджет на год был принят в ноябре 2022 года .             3   
3    Доходы на год были запланированы в размере 28,...             3   
4    Дивизия дивизию введена в состав 19-го бомбард...             2   
..                                                 ...           ...   
295         Прибытие в город спасло Неаполь от захвата             3   
296                     Нейтрализации шансы возросли .             2   
297  Список год описывает спортивные события 2023 г...             2   
298             Цвет в воды являются торфяные болота .             3   
299  Произведён в поручики был награждён золотыми ч...             3   

                     predicate  
0                    ['может']  
1                ['награждён']  
2            ['был', 'принят']  
3    ['бы

### additional data

In [ ]:
from transformers import AutoModelForMaskedLM

def calculate_perplexity(model_name, text):
  """Calculates the perplexity score of a text using AutoModelForMaskedLM.

  Args:
    model_name: The name of the model to use.
    text: The text to score.

  Returns:
    The perplexity score of the text.
  """

  # Load the model.
  model = AutoModelForMaskedLM.from_pretrained(model_name)

  # Tokenize the text.
  tokens = model.tokenizer.tokenize(text)

  # Create a tensor of the token IDs.
  input_ids = torch.tensor(tokens).unsqueeze(0)

  # Move the input IDs to the model's device.
  input_ids = input_ids.to(model.device)

  # Calculate the output logits.
  outputs = model(input_ids, labels=input_ids)
  logits = outputs.logits

  # Calculate the perplexity.
  perplexity = torch.exp(torch.nn.functional.cross_entropy(logits, input_ids, reduction='none')).mean().item()

  return perplexity

In [ ]:
from transformers import AutoModelForMaskedLM

def calculate_textual_accuracy(model_name, text):
  """Calculates the textual accuracy score of a text using AutoModelForMaskedLM.

  Args:
    model_name: The name of the model to use.
    text: The text to score.

  Returns:
    The textual accuracy score of the text.
  """

  # Load the model.
  model = AutoModelForMaskedLM.from_pretrained(model_name)

  # Tokenize the text.
  tokens = model.tokenizer.tokenize(text)

  # Create a tensor of the token IDs.
  input_ids = torch.tensor(tokens).unsqueeze(0)

  # Move the input IDs to the model's device.
  input_ids = input_ids.to(model.device)

  # Calculate the output logits.
  outputs = model(input_ids, labels=input_ids)
  logits = outputs.logits

  # Calculate the accuracy.
  accuracy = torch.nn.functional.softmax(logits, dim=-1).argmax(dim=-1) == input_ids
  accuracy = accuracy.mean().item()

  return accuracy

In [ ]:
from transformers import AutoModelForSeq2SeqLM

def calculate_perplexity(model_name, text):
  """Calculates the perplexity score of a text using AutoModelForSeq2SeqLM.

  Args:
    model_name: The name of the model to use.
    text: The text to score.

  Returns:
    The perplexity score of the text.
  """

  # Load the model.
  model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

  # Tokenize the text.
  tokens = model.tokenizer.tokenize(text)

  # Create a tensor of the token IDs.
  input_ids = torch.tensor(tokens).unsqueeze(0)

  # Move the input IDs to the model's device.
  input_ids = input_ids.to(model.device)

  # Calculate the output logits.
  outputs = model(input_ids, labels=input_ids)
  logits = outputs.logits

  # Calculate the perplexity.
  perplexity = torch.exp(torch.nn.functional.cross_entropy(logits, input_ids, reduction='none')).mean().item()

  return perplexity